name = "klaviyo-proxy"
main = "index.js"
compatibility_date = "2026-06-01"
account_id = "77880cca6d7b7876167d1dbbf0494d26"
workers_dev = true

[[kv_namespaces]]
binding = "CLIENTS_KV"
id = "4b9a981938ac4fc6bebea9ba1f5c8290"

[[kv_namespaces]]
binding = "USERS"
id = "06fd92e3b6a7407f86113278b31e02b2"
